name: Dev Branch Pipeline
on:
  push:
    branches:
      - '*'
      - '!main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo